name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      name: Setup ruby
      with:
        ruby-version: '2.x'
    - name: Build the site
      run: |
        bundle install && bundle exec jekyll build
    - name: Deploy pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v0.4.0
      with:
        target_branch: gh-pages
        build_dir: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
